### ISSUE TITLE
Failed to Start chinadnsd

### ISSUE THREAD

**Issue by mumchristmas** [benjaminlei2007/ss_for_ubnt_usg_p3#1]
> Fri Jan  5 23:28:21 2018 chinadns.c:554 bind: Address already in use
> Fri Jan  5 23:28:21 2018 Can't bind address 0.0.0.0:5353

var/log/chinadnsd.log的记录，watchdog观察到了chinadns启动错误，每分钟都会重试启动，然后继续失败。
症状就是china站点可正常访问，别的不行。

**Comment by benjaminlei2007** [comment]
5353端口被其他应用占了？

**Comment by mumchristmas** [comment]
检查过并无占用，我的USG也没有做过任何手动配置。
看了下其它组件的log，信息比较少，但都正常启动了

**Comment by benjaminlei2007** [comment]
这条错误，一定是端口被占用了，运行 lsof -i:5353
看看目前是哪个程序在监听5353

**Comment by benjaminlei2007** [comment]
如果lsof -i:5353显示端口被chinadns占用，这种情况是，chinadns已经启动了，但pid没有正确保存下来，chinadnsd服务认为chinadns进程没有启动，watchdog一直重启。主要原因是nohup调度进程比较慢，紧接着下一条pgrep可能查不到pid。小概率事件。你可以用ps aux | grep 'chinadns'检查一下后台有没有chinadns，如果有 kill -9 进程ID，watchdog下次检查时，就能把chinadnsd服务正确启动起来了。新的代码删掉了nohup，修复了该小概率错误，你可以用installer/upgrade脚本更新。

**Comment by mumchristmas** [comment]
更新后的测试结果：
lsof -i:5353无反馈，没有进程占用的情况。
另外，每次ps aux | grep 'chinadns'都会跑出不同的pid数字，感觉它自己在反复启动。

网站表现还是和之前一样，无法访问海外site

另外给一个调试的建议：在refresh-ss命令后加个 -stop 参数的选项，不用每次停止都去修改配置文件里的yes和no，比较繁琐。

**Comment by benjaminlei2007** [comment]
。。。。。。我猜到问题了，你需要先sudo -i，切换到root。然后再进行任何操作，admin账户查不出任何东西。我想，你看到的每次pid都在变应该是“grep chinadns”进程。我想你的chinadns服务应该正确启动了，切换到sudo -i，分别用，ps aux |  grep “…”检查dns2socks，ss-local或ssr-local，看看都有进程没，正确解析，chinadns，dns2socks，*-local这三个进程都要，如果没有，检查相应的log。最后检查ss-redir或ssr-redir有没有进程。如果启动了udp，应该有两个redir进程，一个带-U，一个不带-U。

**Comment by mumchristmas** [comment]
傻了，别的命令都记得sudo了，忘记给lsof加。
查到了：

> COMMAND    PID  USER   FD   TYPE DEVICE SIZE NODE NAME
> avahi-dae 2916 avahi   13u  IPv4  19222       UDP *:mdns 
> avahi-dae 2916 avahi   14u  IPv6  19223       UDP *:mdns 

是mdns的进程占用，因为我公司和家里都是Apple设备为主导，所以UniFi的配置里都会打开mdns的选项，默认用到5353口。想要减少冲突的话，可能chinadns的默认端口配置得避让一下

**Comment by benjaminlei2007** [comment]
chinadns的端口改到5354了。用upgrade脚本更新。

**Comment by mumchristmas** [comment]
更新成功，chinadns成功启动，这个ticket的问题应该是解决了。
但还是有海外访问不能的问题，套件还没正常工作，比如访问amazon.com，Chrome报错（ERR_CONNECTION_REFUSED），国内站正常。
log中信息均正常，无报错，dns2socksd.log中有amazon的相关CDN节点缓存记录。

**Comment by benjaminlei2007** [comment]
检查一下iptables的rule，还有ss/ssr配置，尤其是ss，如果启用了obfs plugin，server端也要启用obfs，err_connection_refuse的问题很广，不能判断你那边哪个配置有问题。我自己usg上跑的版本和HEAD版本一致，暂未发现不能访问。还有问题新开issue吧。
