### ISSUE TITLE
关于执行refresh-ss 提示 /init.d/目录下各模块为非可执行文件的错误

### ISSUE THREAD

**Issue by laidycy** [benjaminlei2007/ss_for_ubnt_usg_p3#2]
看说明写的太简陋了，对于我这种基本功不怎么样的人来说，实在是一种煎熬
解决了各种权限不足，bash 没法执行的问题后，碰到了最后一步refersh-ss 出错
提示/init.d 目录下的ss-local ss-redir ss-watchdog等不是一个可执行文件
问下我是哪里做错了嘛？

**Comment by laidycy** [comment]
权限问题 用777解决了，不知道是我个人的问题还是什么情况，usg 的固件是最新的，求指点哪里出错了

**Comment by benjaminlei2007** [comment]
This repo is no longer under maintenance.
